# Generated by Django 3.1.5 on 2021-05-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientModels',
        ),
    ]
