# Generated by Django 3.1.5 on 2021-05-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_nanomodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_user', models.CharField(max_length=100)),
                ('feed_mail', models.EmailField(max_length=254, unique=True)),
                ('feed_text', models.CharField(max_length=300)),
            ],
        ),
    ]
